apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: aiops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: aiops-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
