apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: aiops
  labels:
    app.kubernetes.io/name: aiops-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aiops-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: aiops-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
